export const GAME_DATA = "GAME_DATA"
export const GAME_LOADER = "GAME_LOADER"
export const DATE = "DATE"


export const STANDINGS_DATA = "STANDINGS_DATA"
export const STANDINGS_LOADER = "STANDINGS_LOADER"

export const TEAM_STATS_DATA = "TEAM_STATS_DATA"
export const GAME_STATS_DATA = "GAME_STATS_DATA"
export const TEAM_STATS_LOADER = "TEAM_STATS_LOADER"
export const GAME_STATS_LOADER = "GAME_STATS_LOADER"

export const PLAYER_STATS_DATA = "PLAYER_STATS_DATA"
export const PLAYER_STATS_LOADER = "PLAYER_STATS_LOADER"
export const PLAYER_DATA = "PLAYER_DATA"
export const PLAYER_LOADER = "PLAYER_LOADER"



